module.exports.movie_Service = require("./movie.service")
module.exports.series_Service = require("./series.service")
module.exports.admin_Service = require("./admin.service")
module.exports.doc_Service = require("./documentary.service")
module.exports.city_Service = require("./city.service")
module.exports.state_Service = require("./state.service")