module.exports.movie_Controller = require("./movie.controller")
module.exports.series_Controller = require("./series.controller")
module.exports.admin_Controller = require("./admin.controller")
module.exports.doc_Controller = require("./documentary.controller")
module.exports.city_Controller = require("./city.controller")
module.exports.state_Controller = require("./state.controller")
module.exports.country_Controller = require("./country.controller")
module.exports.bcrypt_Controller = require("./bcrypt.controller")